---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11.4

inputs:
  - name: repo

run:
  path: sh
  dir: repo
  args:
    - -c
    - |
      go get -u golang.org/x/lint/golint
      go mod download
      golint -set_exit_status ./...
      go test -v ./...
  
